### ISSUE TITLE
Collect our thoughts on sourcery and then decide if we keep it in 7 days

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#192]

**Comment by alyssadai** [comment]
Some thoughts from me (will keep updating):

Things I like:
- The reviewer's guide
- "Summary by Sourcery" in the PR description (although this can be redundant with both the reviewer's guide and the PR author-provided description"

Things I don't like:
- Sourcery review comments
  - Reduces readability of the file diff, makes the PR very long, and means that we have to manually resolve extra Sourcery conversations
  - Comments are generally to do with improving code conciseness, which is less essential for us

General: 
- Would be nice to be able to turn off the review itself (or manually trigger it as needed instead of it happening automatically), but keep the reviewer's guide and/or summary

**Comment by surchs** [comment]
Things I like:

- sequence diagrams seem accurate and are helpful
- second pair of eyes is helpful
- makes suggestions

Neutral:

- it seems to look also outside the diff of a PR, so it can spot issues from previous PRs. 
- pretty verbose, i.e. cluttery. But you have to read the diff anyway, so I'm not sure that's actually a downside.

Things I don't like:

- seems pretty over-eager to do easy comments (i.e. mentions every TODO we have and says: should fix TODO)
- not sure it understands our-code / third-party code distinction. I.e. suggest we write unit tests for 3rd party libraries


Ideas:
- we should try to configure some prompts and see if it learns

**Comment by rmanaem** [comment]
Things I like:

- Some sequence diagrams are helpful
- File-level changes table
- Description of the changes PR

Things I don't like:

- Unnecessary review comments and suggestions
- Unnecessary and often inaccurate diagrams and descriptions of the code

It would be helpful if we could configure it to run only when assigned instead of running on every PR and limit/customize its review style and structure.

**Comment by surchs** [comment]
Decision for now is:

- edit the sourcery bot directly to do more of what we like and less of the rest: https://app.sourcery.ai/accounts/152915/repositories/697817508
- give it a week
- decide if we keep the bot around at all or if we remove it

**Comment by alyssadai** [comment]
Based on the feedback, here are the revised basic review settings for Sourcery:
<img width="738" alt="Image" src="https://github.com/user-attachments/assets/025205b4-2aad-4064-8477-e30612c8d772" />
